### ISSUE TITLE
error parsing deploy.yaml: error converting YAML to JSON: yaml: line 32: did not find expected key

### ISSUE THREAD

**Issue by DimanChauncey** [CloudNativeGame/fake-time-injector#9]
When I run command: kubectl apply -f deploy.yaml, I met an error:
> clusterrole.rbac.authorization.k8s.io/fake-time-injector-cr unchanged
> clusterrolebinding.rbac.authorization.k8s.io/fake-time-injector-rb unchanged
> error parsing deploy.yaml: error converting YAML to JSON: yaml: line 32: did not find expected key
> Error from server (BadRequest): error when creating "deploy.yaml": ServiceAccount in version "v1" cannot be handled as a ServiceAccount: strict decoding error: unknown field "namespace"

The deploy.yaml is same with the file in step2: deploy fake-time-injector of README.md

**Comment by songkang7** [comment]
fixed by #10

**Comment by songkang7** [comment]
fix by #10
